name: basic-ci

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: lint
        run: npm run lint
      - name: ts
        run: npm run ts:check
      - name: test
        run: npm run test
      - name: prettier
        run: npm run format -- --check

  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: merge-release
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: bump
        run: |
          git config --local user.email "{{ secrets.GIT_EMAIL }}"
          git config --local user.name "{{ secrets.GIT_NAME }}"
          git stash
          git branch -D master
          git checkout -b master origin/master
          git stash pop
          git add package.json package-lock.json
          git commit -m "bump version $( jq -r .version package.json )"
      - name: push-bump
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
